tabu = int(input('Digite um número pra tabuada: '))
num1 = tabu * 1
num2 = tabu * 2
num3 = tabu * 3
num4 = tabu * 4
num5 = tabu * 5
num6 = tabu * 6
num7 = tabu * 7
num8 = tabu * 8
num9 = tabu * 9
num10 = tabu * 10
print('{} × 1 = {}'.format(tabu, num1))
print('{} × 2 = {}'.format(tabu, num2))
print('{} × 3 = {}'.format(tabu, num3))
print('{} × 4 = {}'.format(tabu, num4))
print('{} × 5 = {}'.format(tabu, num5))
print('{} × 6 = {}'.format(tabu, num6))
print('{} × 7 = {}'.format(tabu, num7))
print('{} × 8 = {}'.format(tabu, num8))
print('{} × 9 = {}'.format(tabu, num9))
print('{} × 10 = {}'.format(tabu, num10))
